// Generated by scripts/generate-spec.mjs — do not edit directly
export const openapi = {
  "openapi": "3.0.3",
  "info": {
    "title": "Terê Verde Online",
    "description": "Api para o Terê Verde Online, sistema de gerenciamento de trilhas, parques e eventos, com avaliação de usuários e informações sobre cada um desses passeios.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3333",
      "description": "Servidor de desenvolvimento"
    }
  ],
  "paths": {
    "/authentication/signup": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Registrar novo usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignUp"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Usuário registrado com sucesso. Verifique seu email para ativação.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Usuário criado, verifique seu email"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos."
          },
          "409": {
            "description": "Email já cadastrado."
          }
        }
      }
    },
    "/authentication/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Autenticar usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Autenticação bem-sucedida. Retorna o token de acesso.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Credenciais inválidas."
          },
          "401": {
            "description": "Não autorizado."
          }
        }
      }
    },
    "/authentication/verify-code": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Consumir código de verificação",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "code": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Código verificado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Código verificado com sucesso"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Código inválido ou expirado."
          }
        }
      }
    },
    "/authentication/token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Verificar validade de um token",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Token válido.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Token é válido"
                    },
                    "data": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "example": "success"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Token inválido."
          },
          "401": {
            "description": "Não autorizado."
          }
        }
      }
    },
    "/authentication/forgot-password": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Solicitar redefinição de senha",
        "description": "Endpoint para solicitar a redefinição de senha (não implementado).",
        "responses": {
          "501": {
            "description": "Não implementado."
          }
        }
      }
    },
    "/rating": {
      "post": {
        "tags": [
          "Rating"
        ],
        "summary": "Criar nova avaliação",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Rating"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Avaliação criada com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rating"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          }
        }
      },
      "delete": {
        "tags": [
          "Rating"
        ],
        "summary": "Deletar avaliação",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "ratingId": {
                    "type": "string"
                  },
                  "outingId": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Avaliação deletada com sucesso."
          },
          "400": {
            "description": "Dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Avaliação não encontrada."
          }
        }
      }
    },
    "/rating/{ratingId}": {
      "put": {
        "tags": [
          "Rating"
        ],
        "summary": "Atualizar avaliação",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "ratingId",
            "in": "path",
            "description": "ID da avaliação.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "rating": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 5,
                    "example": 5
                  },
                  "content": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Avaliação atualizada com sucesso."
          },
          "400": {
            "description": "Dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Avaliação não encontrada."
          }
        }
      }
    },
    "/rating/user/{userId}": {
      "get": {
        "tags": [
          "Rating"
        ],
        "summary": "Buscar avaliações de um usuário",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "ID do usuário.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de avaliações do usuário.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Rating"
                  }
                }
              }
            }
          },
          "400": {
            "description": "ID de usuário inválido."
          }
        }
      }
    },
    "/rating/outing/{outingId}": {
      "get": {
        "tags": [
          "Rating"
        ],
        "summary": "Buscar avaliações de um passeio",
        "parameters": [
          {
            "name": "outingId",
            "in": "path",
            "description": "ID do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de avaliações do passeio.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Rating"
                  }
                }
              }
            }
          },
          "400": {
            "description": "ID de passeio inválido."
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Buscar usuário por ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuário.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário retornado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "ID de usuário inválido."
          },
          "401": {
            "description": "Não autorizado."
          },
          "404": {
            "description": "Usuário não encontrado."
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Atualizar usuário",
        "description": "Endpoint para atualizar um usuário. Requer privilégios de administrador.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuário.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUser"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Usuário atualizado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "ID de usuário inválido ou dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Usuário não encontrado."
          }
        }
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Deletar usuário",
        "description": "Endpoint para deletar um usuário. Requer privilégios de administrador.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do usuário.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Usuário deletado com sucesso."
          },
          "400": {
            "description": "ID de usuário inválido."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Usuário não encontrado."
          }
        }
      }
    },
    "/user": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Buscar perfil do usuário logado",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário retornado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado."
          },
          "404": {
            "description": "Usuário não encontrado."
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Listar todos os usuários",
        "description": "Endpoint para listar todos os usuários. Requer privilégios de administrador.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de usuários retornada com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado, requer privilégios de administrador."
          }
        }
      }
    },
    "/outing": {
      "get": {
        "tags": [
          "Outing"
        ],
        "summary": "Listar passeios",
        "description": "Endpoint para listar todos os passeios com filtros e paginação.",
        "parameters": [
          {
            "name": "take",
            "in": "query",
            "description": "Número de itens por página.",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 10
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "Número da página.",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "Filtrar passeios pelo nome.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "category",
            "in": "query",
            "description": "Filtrar passeios por categoria (Trail, Park, Event). Pode ser uma lista separada por vírgulas.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Ordenar resultados por (title, city).",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "orderBy",
            "in": "query",
            "description": "Ordem de classificação (asc, desc).",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de passeios retornada com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "outings": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/OutingResponse"
                      }
                    },
                    "total": {
                      "type": "integer",
                      "example": 100
                    },
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "pages": {
                      "type": "integer",
                      "example": 10
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor."
          }
        }
      }
    },
    "/outing/{slug}": {
      "get": {
        "tags": [
          "Outing"
        ],
        "summary": "Buscar passeio por slug",
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "Slug do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Passeio retornado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "404": {
            "description": "Passeio não encontrado."
          },
          "500": {
            "description": "Erro interno do servidor."
          }
        }
      }
    },
    "/outing/{id}": {
      "put": {
        "tags": [
          "Outing"
        ],
        "summary": "Atualizar passeio",
        "description": "Endpoint para atualizar um passeio existente.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateOuting"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Passeio atualizado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "ID de passeio inválido ou dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Passeio não encontrado."
          }
        }
      },
      "delete": {
        "tags": [
          "Outing"
        ],
        "summary": "Deletar passeio",
        "description": "Endpoint para deletar um passeio existente.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Passeio deletado com sucesso."
          },
          "400": {
            "description": "ID de passeio inválido."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Passeio não encontrado."
          }
        }
      }
    },
    "/outing/{id}/trail": {
      "post": {
        "tags": [
          "Outing"
        ],
        "summary": "Adicionar trilha a passeio",
        "description": "Endpoint para adicionar uma trilha a um passeio existente.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddTrail"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Trilha adicionada ao passeio com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "ID de passeio inválido ou dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Passeio não encontrado."
          }
        }
      }
    },
    "/outing/{id}/park": {
      "post": {
        "tags": [
          "Outing"
        ],
        "summary": "Adicionar parque a passeio",
        "description": "Endpoint para adicionar um parque a um passeio existente.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddPark"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Parque adicionado ao passeio com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "ID de passeio inválido ou dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Passeio não encontrado."
          }
        }
      }
    },
    "/outing/{id}/event": {
      "post": {
        "tags": [
          "Outing"
        ],
        "summary": "Adicionar evento a passeio",
        "description": "Endpoint para adicionar um evento a um passeio existente.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do passeio.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddEvent"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Evento adicionado ao passeio com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "ID de passeio inválido ou dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          },
          "404": {
            "description": "Passeio não encontrado."
          }
        }
      }
    },
    "/outing/trail": {
      "post": {
        "tags": [
          "Outing"
        ],
        "summary": "Criar passeio de trilha",
        "description": "Endpoint para criar um novo passeio do tipo trilha.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateTrailOuting"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Passeio de trilha criado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          }
        }
      }
    },
    "/outing/park": {
      "post": {
        "tags": [
          "Outing"
        ],
        "summary": "Criar passeio de parque",
        "description": "Endpoint para criar um novo passeio do tipo parque.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateParkOuting"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Passeio de parque criado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          }
        }
      }
    },
    "/outing/event": {
      "post": {
        "tags": [
          "Outing"
        ],
        "summary": "Criar passeio de evento",
        "description": "Endpoint para criar um novo passeio do tipo evento.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateEventOuting"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Passeio de evento criado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OutingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos."
          },
          "401": {
            "description": "Não autorizado."
          },
          "403": {
            "description": "Acesso negado."
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "SignUp": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "john.doe@example.com"
          },
          "password": {
            "type": "string",
            "format": "password",
            "example": "password123"
          }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "example": "john.doe@example.com"
          },
          "password": {
            "type": "string",
            "format": "password",
            "example": "password123"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "role": {
            "type": "string",
            "enum": [
              "USER",
              "ADMIN"
            ]
          },
          "provider": {
            "type": "string",
            "nullable": true
          },
          "googleId": {
            "type": "string",
            "nullable": true
          },
          "avatarUrl": {
            "type": "string",
            "nullable": true
          },
          "verified": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "UpdateUser": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Jane Doe"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "jane.doe@example.com"
          },
          "password": {
            "type": "string",
            "format": "password",
            "example": "newpassword123"
          }
        }
      },
      "Rating": {
        "type": "object",
        "properties": {
          "rating": {
            "type": "integer",
            "minimum": 1,
            "maximum": 5,
            "example": 5
          },
          "content": {
            "type": "string",
            "example": "Ótimo passeio!"
          },
          "outingId": {
            "type": "string"
          }
        }
      },
      "Photo": {
        "type": "object",
        "properties": {
          "alt": {
            "type": "string",
            "example": "Descrição da imagem"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "example": "http://example.com/image.jpg"
          }
        }
      },
      "OpenHour": {
        "type": "object",
        "properties": {
          "dayOfWeek": {
            "type": "integer",
            "minimum": 0,
            "maximum": 6,
            "example": 1
          },
          "openTime": {
            "type": "string",
            "example": "09:00"
          },
          "closeTime": {
            "type": "string",
            "example": "18:00"
          }
        }
      },
      "Trail": {
        "type": "object",
        "properties": {
          "difficulty": {
            "type": "string",
            "enum": [
              "EASY",
              "MEDIUM",
              "HARD"
            ],
            "example": "EASY"
          },
          "duration": {
            "type": "integer",
            "example": 120
          },
          "distance": {
            "type": "number",
            "format": "float",
            "example": 5.5
          },
          "roundTrip": {
            "type": "boolean",
            "example": true
          }
        }
      },
      "Park": {
        "type": "object",
        "properties": {
          "biodiversity": {
            "type": "string",
            "example": "High"
          },
          "maximumCapacity": {
            "type": "integer",
            "example": 100
          }
        }
      },
      "EventDetails": {
        "type": "object",
        "properties": {
          "maximumCapacity": {
            "type": "integer",
            "example": 20
          },
          "startDate": {
            "type": "string",
            "format": "date-time",
            "example": "2025-12-25T10:00:00Z"
          },
          "endDate": {
            "type": "string",
            "format": "date-time",
            "example": "2025-12-25T12:00:00Z"
          }
        }
      },
      "Location": {
        "type": "object",
        "properties": {
          "latitude": {
            "type": "number",
            "format": "float",
            "example": -22.4333
          },
          "longitude": {
            "type": "number",
            "format": "float",
            "example": -42.9667
          },
          "cityId": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "CreateOuting": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "Bela Trilha na Montanha"
          },
          "content": {
            "type": "string",
            "example": "Uma trilha cênica com vistas deslumbrantes."
          },
          "price": {
            "type": "number",
            "example": 25
          },
          "slug": {
            "type": "string",
            "example": "beautiful-mountain-trail"
          },
          "publicAudience": {
            "type": "string",
            "enum": [
              "ALL",
              "PLUS18",
              "PLUS16",
              "PLUS12"
            ]
          },
          "categoryId": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "photos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Photo"
            }
          },
          "openHours": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OpenHour"
            }
          }
        }
      },
      "UpdateOuting": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "Trilha na Montanha Atualizada"
          },
          "content": {
            "type": "string",
            "example": "Uma trilha cênica atualizada com vistas deslumbrantes."
          }
        }
      },
      "AddTrail": {
        "type": "object",
        "properties": {
          "difficulty": {
            "type": "string",
            "enum": [
              "EASY",
              "MEDIUM",
              "HARD"
            ],
            "example": "MEDIUM"
          },
          "duration": {
            "type": "integer",
            "example": 180
          },
          "distance": {
            "type": "number",
            "format": "float",
            "example": 8
          },
          "roundTrip": {
            "type": "boolean",
            "example": false
          }
        }
      },
      "AddPark": {
        "type": "object",
        "properties": {
          "biodiversity": {
            "type": "string",
            "example": "Medium"
          },
          "maximumCapacity": {
            "type": "integer",
            "example": 150
          }
        }
      },
      "AddEvent": {
        "type": "object",
        "properties": {
          "maximumCapacity": {
            "type": "integer",
            "example": 30
          },
          "startDate": {
            "type": "string",
            "format": "date-time",
            "example": "2025-12-30T19:00:00Z"
          },
          "endDate": {
            "type": "string",
            "format": "date-time",
            "example": "2025-12-30T22:00:00Z"
          }
        }
      },
      "CreateTrailOuting": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "Novo Passeio de Trilha"
          },
          "content": {
            "type": "string",
            "example": "Descubra uma nova aventura de trilha."
          },
          "price": {
            "type": "number",
            "example": 30
          },
          "slug": {
            "type": "string",
            "example": "new-trail-outing"
          },
          "publicAudience": {
            "type": "string",
            "enum": [
              "ALL",
              "PLUS18",
              "PLUS16",
              "PLUS12"
            ]
          },
          "categoryId": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "photos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Photo"
            }
          },
          "openHours": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OpenHour"
            }
          },
          "trail": {
            "$ref": "#/components/schemas/Trail"
          }
        }
      },
      "CreateParkOuting": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "Novo Passeio de Parque"
          },
          "content": {
            "type": "string",
            "example": "Explore um parque sereno."
          },
          "price": {
            "type": "number",
            "example": 15
          },
          "slug": {
            "type": "string",
            "example": "new-park-outing"
          },
          "publicAudience": {
            "type": "string",
            "enum": [
              "ALL",
              "PLUS18",
              "PLUS16",
              "PLUS12"
            ]
          },
          "categoryId": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "photos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Photo"
            }
          },
          "openHours": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OpenHour"
            }
          },
          "park": {
            "$ref": "#/components/schemas/Park"
          }
        }
      },
      "CreateEventOuting": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "Novo Passeio de Evento"
          },
          "content": {
            "type": "string",
            "example": "Junte-se a nós para um evento especial."
          },
          "price": {
            "type": "number",
            "example": 50
          },
          "slug": {
            "type": "string",
            "example": "new-event-outing"
          },
          "publicAudience": {
            "type": "string",
            "enum": [
              "ALL",
              "PLUS18",
              "PLUS16",
              "PLUS12"
            ]
          },
          "categoryId": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "photos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Photo"
            }
          },
          "openHours": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OpenHour"
            }
          },
          "event": {
            "$ref": "#/components/schemas/EventDetails"
          }
        }
      },
      "OutingResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "slug": {
            "type": "string"
          },
          "public": {
            "type": "string"
          },
          "categoryId": {
            "type": "integer"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "category": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              }
            }
          },
          "photos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Photo"
            }
          },
          "openHours": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OpenHour"
            }
          },
          "trail": {
            "$ref": "#/components/schemas/Trail"
          },
          "park": {
            "$ref": "#/components/schemas/Park"
          },
          "event": {
            "$ref": "#/components/schemas/EventDetails"
          },
          "ratings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Rating"
            }
          }
        }
      }
    }
  }
} as const;
