import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { load } from "js-yaml";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const docsDir = path.resolve(__dirname, "../src/docs");
const outFile = path.resolve(docsDir, "spec.ts");

function readYaml(filename) {
  return load(readFileSync(path.join(docsDir, filename), "utf-8"));
}

const base = readYaml("openapi.yaml");

for (const file of ["auth.yaml", "rating.yaml", "user.yaml", "outing.yaml"]) {
  const doc = readYaml(file);
  if (doc.paths) {
    Object.assign(base.paths, doc.paths);
  }
}

const output = `// Generated by scripts/generate-spec.mjs — do not edit directly
export const openapi = ${JSON.stringify(base, null, 2)} as const;
`;

writeFileSync(outFile, output, "utf-8");
console.log("Generated src/docs/spec.ts");
